[workspace]
resolver = "2"
members = [
  "crates/nrd-config",
  "crates/nrd-ledger",
  "crates/nrd-proto",
  "crates/nrd-audio",
  "crates/nrd-power",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false
license = "AGPL-3.0-only"

[profile.release]
opt-level = 2
lto = "thin"
panic = "unwind"
