PACKAGE_NAME="neorecall-uac2-name"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="usb_f_uac2"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make KERNELRELEASE=${kernelver} clean"
AUTOINSTALL="yes"
